language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-21mode

env:
  JRUBY_OPTS="--2.1 --server -Dcext.enabled=false -Xcompile.invokedynamic=false"

gemfile:
  - gemfiles/rake10.gemfile
  - gemfiles/rake11.gemfile

before_install:
  - gem install bundler -v '~> 1.11'